title: Bartusch - Holz und Handwerk
description: Holzbearbeitung und MÃ¶belbau aus einer Hand
url: "https://bartusch-handwerk.de"
baseurl: ""

permalink: pretty

include:
  - _pages

sass:
  style: compressed

exclude:
  - Gemfile
  - Gemfile.lock
  - docs/
  - README.md
