title: Bartusch - Holz und Handwerk
description: Holzbearbeitung und MÃ¶belbau aus einer Hand
url: "https://bartusch-handwerk.de"
baseurl: ""

permalink: pretty

plugins:
  - jekyll-redirect-from

include:
  - _pages

sass:
  style: compressed

webrick:
  headers:
    "/*.mp4":
      Content-Type: video/mp4
    "/*.mkv":
      Content-Type: video/x-matroska

exclude:
  - Gemfile
  - Gemfile.lock
  - docs/
  - README.md
